/*
 * This file is generated by jOOQ.
 */
package io.quarkus.ext.jooq.demo.tables.pojos;

import java.io.Serializable;

import javax.annotation.Generated;

import io.quarkus.runtime.annotations.RegisterForReflection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@RegisterForReflection
@Generated("2020-08-21")
public class Departments implements Serializable {

    private static final long serialVersionUID = 971173349;

    private String deptNo;

    private String deptName;

    public Departments() {
    }

    public Departments(Departments value) {
        this.deptNo = value.deptNo;
        this.deptName = value.deptName;
    }

    public Departments(String deptNo, String deptName) {
        this.deptNo = deptNo;
        this.deptName = deptName;
    }

    public String getDeptNo() {
        return this.deptNo;
    }

    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    public String getDeptName() {
        return this.deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Departments (");
        sb.append(deptNo);
        sb.append(", ").append(deptName);
        sb.append(")");
        return sb.toString();
    }

    /**
     * Subclass may override this method
     */
    @Override
    public Departments clone() throws CloneNotSupportedException {
        Departments departments = new Departments();
        departments.deptNo = this.deptNo;
        departments.deptName = this.deptName;
        return departments;
    }
}
