/*
 * This file is generated by jOOQ.
 */
package io.quarkus.ext.jooq.demo.tables.pojos;

import java.io.Serializable;
import java.time.LocalDate;

import javax.annotation.Generated;

import io.quarkus.runtime.annotations.RegisterForReflection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@RegisterForReflection
@Generated("2020-08-21")
public class DeptManager implements Serializable {

    private static final long serialVersionUID = 1242359783;

    private Integer empNo;

    private String deptNo;

    private LocalDate fromDate;

    private LocalDate toDate;

    public DeptManager() {
    }

    public DeptManager(DeptManager value) {
        this.empNo = value.empNo;
        this.deptNo = value.deptNo;
        this.fromDate = value.fromDate;
        this.toDate = value.toDate;
    }

    public DeptManager(Integer empNo, String deptNo, LocalDate fromDate, LocalDate toDate) {
        this.empNo = empNo;
        this.deptNo = deptNo;
        this.fromDate = fromDate;
        this.toDate = toDate;
    }

    public Integer getEmpNo() {
        return this.empNo;
    }

    public void setEmpNo(Integer empNo) {
        this.empNo = empNo;
    }

    public String getDeptNo() {
        return this.deptNo;
    }

    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    public LocalDate getFromDate() {
        return this.fromDate;
    }

    public void setFromDate(LocalDate fromDate) {
        this.fromDate = fromDate;
    }

    public LocalDate getToDate() {
        return this.toDate;
    }

    public void setToDate(LocalDate toDate) {
        this.toDate = toDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DeptManager (");
        sb.append(empNo);
        sb.append(", ").append(deptNo);
        sb.append(", ").append(fromDate);
        sb.append(", ").append(toDate);
        sb.append(")");
        return sb.toString();
    }

    /**
     * Subclass may override this method
     */
    @Override
    public DeptManager clone() throws CloneNotSupportedException {
        DeptManager deptManager = new DeptManager();
        deptManager.empNo = this.empNo;
        deptManager.deptNo = this.deptNo;
        deptManager.fromDate = this.fromDate;
        deptManager.toDate = this.toDate;
        return deptManager;
    }
}
