/*
 * This file is generated by jOOQ.
 */
package io.quarkus.ext.jooq.demo.tables.pojos;

import java.io.Serializable;
import java.time.LocalDate;

import javax.annotation.Generated;

import io.quarkus.runtime.annotations.RegisterForReflection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@RegisterForReflection
@Generated("2020-08-21")
public class Salaries implements Serializable {

    private static final long serialVersionUID = 545426695;

    private Integer empNo;

    private Integer salary;

    private LocalDate fromDate;

    private LocalDate toDate;

    public Salaries() {
    }

    public Salaries(Salaries value) {
        this.empNo = value.empNo;
        this.salary = value.salary;
        this.fromDate = value.fromDate;
        this.toDate = value.toDate;
    }

    public Salaries(Integer empNo, Integer salary, LocalDate fromDate, LocalDate toDate) {
        this.empNo = empNo;
        this.salary = salary;
        this.fromDate = fromDate;
        this.toDate = toDate;
    }

    public Integer getEmpNo() {
        return this.empNo;
    }

    public void setEmpNo(Integer empNo) {
        this.empNo = empNo;
    }

    public Integer getSalary() {
        return this.salary;
    }

    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    public LocalDate getFromDate() {
        return this.fromDate;
    }

    public void setFromDate(LocalDate fromDate) {
        this.fromDate = fromDate;
    }

    public LocalDate getToDate() {
        return this.toDate;
    }

    public void setToDate(LocalDate toDate) {
        this.toDate = toDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Salaries (");
        sb.append(empNo);
        sb.append(", ").append(salary);
        sb.append(", ").append(fromDate);
        sb.append(", ").append(toDate);
        sb.append(")");
        return sb.toString();
    }

    /**
     * Subclass may override this method
     */
    @Override
    public Salaries clone() throws CloneNotSupportedException {
        Salaries salaries = new Salaries();
        salaries.empNo = this.empNo;
        salaries.salary = this.salary;
        salaries.fromDate = this.fromDate;
        salaries.toDate = this.toDate;
        return salaries;
    }
}
