/*
 * This file is generated by jOOQ.
 */
package io.quarkus.ext.jooq.demo.tables.pojos;

import java.io.Serializable;
import java.time.LocalDate;

import javax.annotation.Generated;

import io.quarkus.runtime.annotations.RegisterForReflection;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@RegisterForReflection
@Generated("2020-08-21")
public class Titles implements Serializable {

    private static final long serialVersionUID = 1399053133;

    private Integer empNo;

    private String title;

    private LocalDate fromDate;

    private LocalDate toDate;

    public Titles() {
    }

    public Titles(Titles value) {
        this.empNo = value.empNo;
        this.title = value.title;
        this.fromDate = value.fromDate;
        this.toDate = value.toDate;
    }

    public Titles(Integer empNo, String title, LocalDate fromDate, LocalDate toDate) {
        this.empNo = empNo;
        this.title = title;
        this.fromDate = fromDate;
        this.toDate = toDate;
    }

    public Integer getEmpNo() {
        return this.empNo;
    }

    public void setEmpNo(Integer empNo) {
        this.empNo = empNo;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public LocalDate getFromDate() {
        return this.fromDate;
    }

    public void setFromDate(LocalDate fromDate) {
        this.fromDate = fromDate;
    }

    public LocalDate getToDate() {
        return this.toDate;
    }

    public void setToDate(LocalDate toDate) {
        this.toDate = toDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Titles (");
        sb.append(empNo);
        sb.append(", ").append(title);
        sb.append(", ").append(fromDate);
        sb.append(", ").append(toDate);
        sb.append(")");
        return sb.toString();
    }

    /**
     * Subclass may override this method
     */
    @Override
    public Titles clone() throws CloneNotSupportedException {
        Titles titles = new Titles();
        titles.empNo = this.empNo;
        titles.title = this.title;
        titles.fromDate = this.fromDate;
        titles.toDate = this.toDate;
        return titles;
    }
}
