/*
 * This file is generated by jOOQ.
 */
package io.quarkus.ext.jooq.demo.enums;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;
import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Generated("2020-08-21")
public enum EmployeesGender implements EnumType {

    M("M"), F("F");

    private final String literal;

    private EmployeesGender(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "employees_gender";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
