/*
 * This file is generated by jOOQ.
 */
package io.quarkus.ext.jooq.demo;

import org.jooq.impl.CatalogImpl;
import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Generated("2020-08-21")
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = -1795029326;

    /**
     * The reference instance of <code>DEFAULT_CATALOG</code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }
}
