/*
 * This file is generated by jOOQ.
 */
package io.quarkus.ext.jooq.demo;

import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import io.quarkus.ext.jooq.demo.tables.QDepartments;
import io.quarkus.ext.jooq.demo.tables.QDeptEmp;
import io.quarkus.ext.jooq.demo.tables.QDeptManager;
import io.quarkus.ext.jooq.demo.tables.QEmployees;
import io.quarkus.ext.jooq.demo.tables.QSalaries;
import io.quarkus.ext.jooq.demo.tables.QTitles;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Generated("2020-08-21")
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -353222535;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }

    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(QDepartments.$, QDeptEmp.$, QDeptManager.$, QEmployees.$, QSalaries.$, QTitles.$);
    }
}
