/*
 * This file is generated by jOOQ.
 */
package io.quarkus.ext.jooq.demo.tables;

import java.util.Arrays;
import java.util.List;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;

import io.quarkus.ext.jooq.demo.DefaultSchema;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Generated("2020-08-21")
public class QDepartments extends TableImpl<Record> {

    private static final long serialVersionUID = -808350841;

    /**
     * The reference instance of <code>departments</code>
     */
    public static final QDepartments $ = new QDepartments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>departments.dept_no</code>.
     */
    public final TableField<Record, String> deptNo = createField(DSL.name("dept_no"), org.jooq.impl.SQLDataType.CHAR(4).nullable(false), this, "");

    /**
     * The column <code>departments.dept_name</code>.
     */
    public final TableField<Record, String> deptName = createField(DSL.name("dept_name"), org.jooq.impl.SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * Create a <code>departments</code> table reference
     */
    public QDepartments() {
        this(DSL.name("departments"), null);
    }

    /**
     * Create an aliased <code>departments</code> table reference
     */
    public QDepartments(String alias) {
        this(DSL.name(alias), $);
    }

    /**
     * Create an aliased <code>departments</code> table reference
     */
    public QDepartments(Name alias) {
        this(alias, $);
    }

    private QDepartments(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private QDepartments(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(QDepartments.$, "KEY_departments_PRIMARY", new TableField[] { QDepartments.$.deptNo }, true);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Internal.createUniqueKey(QDepartments.$, "KEY_departments_PRIMARY", new TableField[] { QDepartments.$.deptNo }, true), Internal.createUniqueKey(QDepartments.$, "KEY_departments_dept_name", new TableField[] { QDepartments.$.deptName }, true));
    }

    @Override
    public QDepartments as(String alias) {
        return new QDepartments(DSL.name(alias), this);
    }

    @Override
    public QDepartments as(Name alias) {
        return new QDepartments(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QDepartments rename(String name) {
        return new QDepartments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QDepartments rename(Name name) {
        return new QDepartments(name, null);
    }
}
