/*
 * This file is generated by jOOQ.
 */
package io.quarkus.ext.jooq.demo.tables;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;

import io.quarkus.ext.jooq.demo.DefaultSchema;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Generated("2020-08-21")
public class QSalaries extends TableImpl<Record> {

    private static final long serialVersionUID = 1814306131;

    /**
     * The reference instance of <code>salaries</code>
     */
    public static final QSalaries $ = new QSalaries();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>salaries.emp_no</code>.
     */
    public final TableField<Record, Integer> empNo = createField(DSL.name("emp_no"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>salaries.salary</code>.
     */
    public final TableField<Record, Integer> salary = createField(DSL.name("salary"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>salaries.from_date</code>.
     */
    public final TableField<Record, LocalDate> fromDate = createField(DSL.name("from_date"), org.jooq.impl.SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>salaries.to_date</code>.
     */
    public final TableField<Record, LocalDate> toDate = createField(DSL.name("to_date"), org.jooq.impl.SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * Create a <code>salaries</code> table reference
     */
    public QSalaries() {
        this(DSL.name("salaries"), null);
    }

    /**
     * Create an aliased <code>salaries</code> table reference
     */
    public QSalaries(String alias) {
        this(DSL.name(alias), $);
    }

    /**
     * Create an aliased <code>salaries</code> table reference
     */
    public QSalaries(Name alias) {
        this(alias, $);
    }

    private QSalaries(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private QSalaries(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(QSalaries.$, "KEY_salaries_PRIMARY", new TableField[] { QSalaries.$.empNo, QSalaries.$.fromDate }, true);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Internal.createUniqueKey(QSalaries.$, "KEY_salaries_PRIMARY", new TableField[] { QSalaries.$.empNo, QSalaries.$.fromDate }, true));
    }

    @Override
    public QSalaries as(String alias) {
        return new QSalaries(DSL.name(alias), this);
    }

    @Override
    public QSalaries as(Name alias) {
        return new QSalaries(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QSalaries rename(String name) {
        return new QSalaries(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QSalaries rename(Name name) {
        return new QSalaries(name, null);
    }
}
