/*
 * This file is generated by jOOQ.
 */
package io.quarkus.ext.jooq.demo.tables;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;

import io.quarkus.ext.jooq.demo.DefaultSchema;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Generated("2020-08-21")
public class QTitles extends TableImpl<Record> {

    private static final long serialVersionUID = 1955351010;

    /**
     * The reference instance of <code>titles</code>
     */
    public static final QTitles $ = new QTitles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>titles.emp_no</code>.
     */
    public final TableField<Record, Integer> empNo = createField(DSL.name("emp_no"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>titles.title</code>.
     */
    public final TableField<Record, String> title = createField(DSL.name("title"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>titles.from_date</code>.
     */
    public final TableField<Record, LocalDate> fromDate = createField(DSL.name("from_date"), org.jooq.impl.SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>titles.to_date</code>.
     */
    public final TableField<Record, LocalDate> toDate = createField(DSL.name("to_date"), org.jooq.impl.SQLDataType.LOCALDATE, this, "");

    /**
     * Create a <code>titles</code> table reference
     */
    public QTitles() {
        this(DSL.name("titles"), null);
    }

    /**
     * Create an aliased <code>titles</code> table reference
     */
    public QTitles(String alias) {
        this(DSL.name(alias), $);
    }

    /**
     * Create an aliased <code>titles</code> table reference
     */
    public QTitles(Name alias) {
        this(alias, $);
    }

    private QTitles(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private QTitles(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(QTitles.$, "KEY_titles_PRIMARY", new TableField[] { QTitles.$.empNo, QTitles.$.title, QTitles.$.fromDate }, true);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Internal.createUniqueKey(QTitles.$, "KEY_titles_PRIMARY", new TableField[] { QTitles.$.empNo, QTitles.$.title, QTitles.$.fromDate }, true));
    }

    @Override
    public QTitles as(String alias) {
        return new QTitles(DSL.name(alias), this);
    }

    @Override
    public QTitles as(Name alias) {
        return new QTitles(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QTitles rename(String name) {
        return new QTitles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QTitles rename(Name name) {
        return new QTitles(name, null);
    }
}
